add_lunch_combo sabresd_7d-user
add_lunch_combo sabresd_7d-userdebug
add_lunch_combo pico_imx7-user
add_lunch_combo pico_imx7-userdebug
add_lunch_combo tep1_imx7-user
add_lunch_combo tep1_imx7-userdebug
